<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>eKesihatan Weekly Appointment Report</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color: #111827; font-size: 12px; }
        .header { display: table; width: 100%; margin-bottom: 18px; border-bottom: 2px solid #1f4f46; padding-bottom: 12px; }
        .brand { display: table-cell; vertical-align: middle; }
        .brand h1 { margin: 0; font-size: 22px; color: #1f4f46; }
        .meta { display: table-cell; text-align: right; vertical-align: middle; font-size: 11px; color: #4b5563; }
        .summary { width: 100%; border-collapse: collapse; margin: 14px 0 18px; }
        .summary td { border: 1px solid #d1d5db; padding: 10px; text-align: center; }
        .summary strong { display: block; font-size: 18px; color: #1f4f46; }
        table.details { width: 100%; border-collapse: collapse; }
        table.details th, table.details td { border: 1px solid #d1d5db; padding: 7px; text-align: center; }
        table.details th { background: #edf7f4; color: #1f4f46; }
        .footer { margin-top: 18px; font-size: 10px; color: #6b7280; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">
            <h1>eKesihatan</h1>
            <div>Weekly Appointment Report</div>
        </div>
        <div class="meta">
            Month: {{ $month->format('F Y') }}<br>
            Week: {{ $week }}<br>
            Period: {{ $start->format('d M Y') }} - {{ $end->format('d M Y') }}<br>
            Generated: {{ now()->format('d M Y, h:i A') }}
        </div>
    </div>

    <table class="summary">
        <tr>
            <td><strong>{{ $summary['total'] }}</strong>Total Appointments</td>
            <td><strong>{{ $summary['completed'] }}</strong>Completed</td>
            <td><strong>{{ $summary['noShow'] }}</strong>No-show</td>
            <td><strong>{{ $summary['cancelled'] }}</strong>Cancelled</td>
        </tr>
    </table>

    <table class="details">
        <thead>
            <tr>
                <th>No.</th>
                <th>Date</th>
                <th>Time</th>
                <th>Patient</th>
                <th>Doctor</th>
                <th>Service</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($appointments as $appointment)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $appointment->scheduled_at->format('d M Y') }}</td>
                    <td>{{ $appointment->scheduled_at->format('h:i A') }}</td>
                    <td>{{ $appointment->patient->name ?? '-' }}</td>
                    <td>{{ $appointment->doctor->name ?? '-' }}</td>
                    <td>{{ $appointment->service?->name ?? 'General' }}</td>
                    <td>{{ ucfirst($appointment->status) }}</td>
                </tr>
            @empty
                <tr><td colspan="7">No appointments found for this week.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by eKesihatan Clinic Management System.</div>
</body>
</html>
